### ISSUE TITLE
Doesn't compile in Manjaro

### ISSUE THREAD

**Issue by CagedWings** [Pedro-Beirao/dsda-launcher#3]
I tried installing the launcher in my Manjaro system, but it doesn't compile. I followed the macOS installation guide.
I tried copying the dsda binary and wad inside the dsda-launcher folder and creating a symlink to them, but the same error kept apearing.
```
$ cd dsda-launcher/
$ rm dsda-doom.wad 
$ ln -s /usr/local/share/games/doom/dsda-doom.wad .
$ ln -s /usr/bin/dsda-doom .
$ mkdir build && cd build
$ qmake ..
$ make
/usr/bin/uic ../console.ui -o ui_console.h
/usr/bin/uic ../mainwindow.ui -o ui_mainwindow.h
/usr/bin/uic ../settings.ui -o ui_settings.h
g++ -c -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DAPP_NAME=dsda-launcher -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../dsda-launcher -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o console.o ../console.cpp
g++ -c -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DAPP_NAME=dsda-launcher -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../dsda-launcher -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o main.o ../main.cpp
g++ -c -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DAPP_NAME=dsda-launcher -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../dsda-launcher -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o mainwindow.o ../mainwindow.cpp
../mainwindow.cpp: In function ‘QString lowerCase(std::string)’:
../mainwindow.cpp:187:18: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  187 |     for(int i=0;i<word.length();i++)
      |                 ~^~~~~~~~~~~~~~
../mainwindow.cpp: In member function ‘void MainWindow::dropFile(QString)’:
../mainwindow.cpp:849:59: error: ‘class QStringList’ has no member named ‘remove’; did you mean ‘removeAt’?
  849 |                                                     files.remove(i);
      |                                                           ^~~~~~
      |                                                           removeAt
../mainwindow.cpp:875:51: error: ‘class QStringList’ has no member named ‘remove’; did you mean ‘removeAt’?
  875 |                                             files.remove(i);
      |                                                   ^~~~~~
      |                                                   removeAt
../mainwindow.cpp:819:34: warning: unused variable ‘isRecursive’ [-Wunused-variable]
  819 |                             bool isRecursive = settings.value("pwadrecursive").toBool();
      |                                  ^~~~~~~~~~~
../mainwindow.cpp: In member function ‘void MainWindow::foo()’:
../mainwindow.cpp:1141:32: warning: ‘static bool QProcess::startDetached(const QString&)’ is deprecated: Use QProcess::startDetached(const QString &program, const QStringList &arguments) instead [-Wdeprecated-declarations]
 1141 |         QProcess::startDetached(("explorer \""+QCoreApplication::applicationDirPath().toStdString() + "\"").c_str());
      |         ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt/QtCore/QProcess:1,
                 from ../mainwindow.h:6,
                 from ../mainwindow.cpp:8:
/usr/include/qt/QtCore/qprocess.h:280:17: note: declared here
  280 |     static bool startDetached(const QString &command);
      |                 ^~~~~~~~~~~~~
../mainwindow.cpp: In member function ‘void MainWindow::finished(int, QProcess::ExitStatus)’:
../mainwindow.cpp:1179:31: warning: unused parameter ‘exitCode’ [-Wunused-parameter]
 1179 | void MainWindow::finished(int exitCode, QProcess::ExitStatus exitStatus)
      |                           ~~~~^~~~~~~~
../mainwindow.cpp:1179:62: warning: unused parameter ‘exitStatus’ [-Wunused-parameter]
 1179 | void MainWindow::finished(int exitCode, QProcess::ExitStatus exitStatus)
      |                                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
../mainwindow.cpp: In member function ‘void MainWindow::on_LaunchGameButton_clicked(bool, bool, std::string)’:
../mainwindow.cpp:1290:31: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned in ’} [-Wsign-compare]
 1290 |                 for(int i=0; i<fileToAdd.length();i++)
      |                              ~^~~~~~~~~~~~~~~~~~~
../mainwindow.cpp:1455:31: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
 1455 |             for( size_t i=0; i<p.length(); i++){
      |                              ~^~~~~~~~~~~
../mainwindow.cpp:1456:21: error: ambiguous overload for ‘operator[]’ (operand types are ‘QString’ and ‘size_t’ {aka ‘long unsigned int’})
 1456 |                 if(p[i]=='/' || p[i]=='\\')
      |                     ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from ../mainwindow.h:4,
                 from ../mainwindow.cpp:8:
/usr/include/qt/QtCore/qstring.h:1073:20: note: candidate: ‘const QChar QString::operator[](int) const’
 1073 | inline const QChar QString::operator[](int i) const
      |                    ^~~~~~~
/usr/include/qt/QtCore/qstring.h:1338:17: note: candidate: ‘QCharRef QString::operator[](int)’
 1338 | inline QCharRef QString::operator[](int i)
      |                 ^~~~~~~
/usr/include/qt/QtCore/qstring.h:1075:20: note: candidate: ‘const QChar QString::operator[](uint) const’
 1075 | inline const QChar QString::operator[](uint i) const
      |                    ^~~~~~~
/usr/include/qt/QtCore/qstring.h:1340:17: note: candidate: ‘QCharRef QString::operator[](uint)’
 1340 | inline QCharRef QString::operator[](uint i)
      |                 ^~~~~~~
../mainwindow.cpp:1456:34: error: ambiguous overload for ‘operator[]’ (operand types are ‘QString’ and ‘size_t’ {aka ‘long unsigned int’})
 1456 |                 if(p[i]=='/' || p[i]=='\\')
      |                                  ^
In file included from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qmainwindow.h:44,
                 from /usr/include/qt/QtWidgets/QMainWindow:1,
                 from ../mainwindow.h:4,
                 from ../mainwindow.cpp:8:
/usr/include/qt/QtCore/qstring.h:1073:20: note: candidate: ‘const QChar QString::operator[](int) const’
 1073 | inline const QChar QString::operator[](int i) const
      |                    ^~~~~~~
/usr/include/qt/QtCore/qstring.h:1338:17: note: candidate: ‘QCharRef QString::operator[](int)’
 1338 | inline QCharRef QString::operator[](int i)
      |                 ^~~~~~~
/usr/include/qt/QtCore/qstring.h:1075:20: note: candidate: ‘const QChar QString::operator[](uint) const’
 1075 | inline const QChar QString::operator[](uint i) const
      |                    ^~~~~~~
/usr/include/qt/QtCore/qstring.h:1340:17: note: candidate: ‘QCharRef QString::operator[](uint)’
 1340 | inline QCharRef QString::operator[](uint i)
      |                 ^~~~~~~
../mainwindow.cpp: In member function ‘void MainWindow::on_iwadSelect_currentIndexChanged(int)’:
../mainwindow.cpp:1699:56: warning: unused parameter ‘index’ [-Wunused-parameter]
 1699 | void MainWindow::on_iwadSelect_currentIndexChanged(int index)
      |                                                    ~~~~^~~~~
../mainwindow.cpp: In member function ‘void MainWindow::on_comboBox_currentIndexChanged(int)’:
../mainwindow.cpp:1932:54: warning: unused parameter ‘index’ [-Wunused-parameter]
 1932 | void MainWindow::on_comboBox_currentIndexChanged(int index) // This is the category box (UV speed, UV max, etc)
      |                                                  ~~~~^~~~~
../mainwindow.cpp: In member function ‘void MainWindow::on_wadLName_textChanged(const QString&)’:
../mainwindow.cpp:2277:57: warning: unused parameter ‘arg1’ [-Wunused-parameter]
 2277 | void MainWindow::on_wadLName_textChanged(const QString &arg1)
      |                                          ~~~~~~~~~~~~~~~^~~~
../mainwindow.cpp: In member function ‘void MainWindow::on_wadLName_2_textChanged(const QString&)’:
../mainwindow.cpp:2283:59: warning: unused parameter ‘arg1’ [-Wunused-parameter]
 2283 | void MainWindow::on_wadLName_2_textChanged(const QString &arg1)
      |                                            ~~~~~~~~~~~~~~~^~~~
make: *** [Makefile:751: mainwindow.o] Error 1
```
qmake version:
```
$ qmake --version
QMake version 3.1
Using Qt version 5.15.3 in /usr/lib
```

**Comment by Vulldozer** [comment]
I tried compiling it with qmake v3.1 with: 
-Qt version 5.12.8 - Build failed - Error 1
-Qt version 6.2.4 - Build success.

The solution for now is to download the latest version from the Qt website.

For compiling in terminal use the newly installed qmake in "QtInstallDirectoryHere/VersionNumberHere/gcc_64/bin/qmake" (for example: "~/qt/6.2.4/gcc_64/bin/qmake").

For compiling in GUI, run the Qt Creator program, open the project file in dsda-launcher/dsda-launcher.pro, click the build button and then the run.

**Comment by Vulldozer** [comment]
@Pedro-Beirao The build instructions mention the project was tested on 5.15.2 but it looks like it doesn't work with 5.15.3
Is it still supposed to work on 5.15.0 and up?

**Comment by Pedro-Beirao** [comment]
At the start of this project, I was using 5.15.2, but now Im using 6.2.2.
Some features I used seem to not work in older versions.
I will update the build instructions.

**Comment by Pedro-Beirao** [comment]
Also, copying dsda-doom and dsda-doom.wad to the folder before compiling is only necessary on MacOS since it creates and app bundle.
On Windows and Linux you will only need to copy/symlink it when running the launcher.

**Comment by CagedWings** [comment]
$ qmake6 --version
QMake version 3.1
Using Qt version 6.3.0 in /usr/lib

**Comment by Contmotore** [comment]
> The solution for now is to download the latest version from the Qt website.

That didn't work for me in Arch Linux.

`$ qmake ..`
`$ make`
```
g++ -c -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC -DAPP_NAME=dsda-launcher -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../dsda-launcher -I. -I/home/contmotore/Qt/6.2.4/gcc_64/include -I/home/contmotore/Qt/6.2.4/gcc_64/include/QtWidgets -I/home/contmotore/Qt/6.2.4/gcc_64/include/QtGui -I/home/contmotore/Qt/6.2.4/gcc_64/include/QtNetwork -I/home/contmotore/Qt/6.2.4/gcc_64/include/QtConcurrent -I/home/contmotore/Qt/6.2.4/gcc_64/include/QtCore -I. -I. -I/home/contmotore/Qt/6.2.4/gcc_64/mkspecs/linux-g++ -o mainwindow.o ../mainwindow.cpp
In file included from ../mainwindow.cpp:9:
././ui_mainwindow.h:13:10: fatal error: QtWidgets/QAction: No such file or directory
   13 | #include <QtWidgets/QAction>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1818: mainwindow.o] Error 1```

**Comment by Pedro-Beirao** [comment]
ui_mainwindow.h is a file created automatically by Qt, so I don't understand why it is failing.
I'll install Qt 6.2.4, to see I can spot the problem.
Still, I plan on keep using Qt 6.2.2, so if the problem is with the Qt version, then the only solution will probably be to downgrade
